# Docker Compose override for host networking
# This version uses host networking to solve Docker IP detection issues
# Usage: docker compose -f docker-compose.yml -f docker-compose.host.yml up -d

services:
  backend:
    network_mode: host
    networks: []  # Remove custom networks when using host mode
    ports: []     # Remove port mapping when using host mode

# Networks section is not needed in host mode
networks: {}